export const ADD_EXERCISE = 'ADD_EXERCISE';
export const ADD_SET = 'ADD_SET';
export const ADD_CHECKED_CHECKBOX_ID = 'ADD_CHECKED_CHECKBOX_ID';
export const DELETE_CHECKED = 'DELETE_CHECKED';
export const CHANGE_EXERCISE_DISPLAY = 'CHANGE_EXERCISE_DISPLAY';
export const EMPTY_CHECKED_LISTS = 'EMPTY_CHECKED_LISTS';
